# workflow name
name: Hexo Blog CI

# master branch on push, auto run
on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  
jobs:
  build: 
    runs-on: ubuntu-latest 
        
    steps:
    # check it to your workflow can access it
    # from: https://github.com/actions/checkout
    - name: Checkout Repository master branch
      uses: actions/checkout@master 
      
    # from: https://github.com/actions/setup-node  
    - name: Setup Node.js 12.x 
      uses: actions/setup-node@master
      with:
        node-version: "12.x" 
    - name: Setup Hexo Dependencies
      run: |
        npm config set registry https://registry.npm.taobao.org/ 
        npm install hexo-cli@6.1.0 -g --save
        npm install 
    - name: Build artifact
      run: |
        hexo clean
        hexo generate 
        tar --dereference --hard-dereference --directory public/ -cvf artifact.tar . 
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: github-pages
        path: ./artifact.tar
        if-no-files-found: warn
  depoly: 
    needs: build
    permissions:
      id-token: write
      pages: write
      contents: read
      deployments: write
    runs-on: ubuntu-latest 
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
    # check it to your workflow can access it
    # from: https://github.com/actions/checkout
    # - name: Deploy
    # uses: JamesIves/github-pages-deploy-action@v4.2.5
    #     with:
    #       branch: gh-pages # The branch the action should deploy to.
    #       folder: build # The folder the action should deploy.
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v1





